#! /usr/bin/env python

import rospy
from hardware_bridge.bridge import BookleBridge 


if __name__ == '__main__':
    try:
    	my_bridge = BookleBridge()
        my_bridge.start()
    except rospy.ROSInterruptException:
        pass


